services:
    db:
        image: mysql:8.0
        ports:
            - "3306:3306"
        env_file:
            - ./docker/db/.env
        volumes:
            - ./docker/db/data:/var/lib/mysql:rw
            - ./docker/db/config:/etc/mysql/conf.d
        command: mysqld --sql_mode=""

    php:
        build: ./docker/php/8.4/
        volumes:
            - ./docker/php/app.ini:/usr/local/etc/php/conf.d/docker-php-ext-app.ini:ro
            - ./docker/logs/app:/var/www/app/var/log:cached
            - .:/var/www/app:cached
        working_dir: /var/www/app
        links:
            - db
        env_file:
            - ./docker/php/.env

    webserver:
        image: nginx:1
        depends_on:
            - php
        volumes:
            - ./docker/webserver/app.conf:/etc/nginx/conf.d/default.conf:ro
            - ./docker/logs/webserver/:/var/log/nginx:cached
            - .:/var/www/app:ro
        ports:
            - "80:80"

    mailcatcher:
        image: schickling/mailcatcher
        ports:
            - "1080:1080"

    adminer:
        image: adminer:4.8.1
        volumes:
            - ./docker/adminer/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
        ports:
          - "8080:8080"
